version: '3.8'

services:
  node-service:
    build: ./node-service
    ports:
      - "8080:8080"
    networks:
      - microservices-network

  python-service:
    build: ./python-service
    ports:
      - "5000:5000"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
